### ISSUE TITLE
Write correct format id for kv3 particles

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveResourceFormat#132]
We currently hardcode the `<!-- kv3` header format. I changed it to output the correct guid, but it will still output `generic` instead of stuff like `vpcf19`

**Comment by kristiker** [comment]
Would have to store a guid:tag mapping in library. This data is also not required for decompilation as the tools only care about the guid.

**Comment by kristiker** [comment]
Not required, so not worth holding a list of these IDs.
