### ISSUE TITLE
Add support for VFE files

### ISSUE THREAD

**Issue by MattFiler** [ValveResourceFormat/ValveResourceFormat#142]
VFE files seem to define face pose data - examples of decompiled VFE files can be found within CS:GO, inside the "expressions" directory.

**Comment by xPaw** [comment]
Source 1 is out of scope here. Do these expressions exist in S2 and if so, do they have same format?

**Comment by MattFiler** [comment]
Yeah, they're used in Source 2 - confirmed in Dota 2 and Dota Underlords (potentially Artifact also, but I don't know it). Seems to use the same format.

**Comment by MattFiler** [comment]
Ok took a quick look at this and got a bit of info. I'm unsure exactly what data the VFEs contain relating to face posing so I'm struggling to work out the usefulness of some values, but here's a bit of insight into the file's structure anyways.

Header starts at position 72.

- (int) Length of the file in bytes
- 16 bytes of unknown
- (int) Start of the first 0xFF block
- (int) The number of keys (useful for reading just about anything given the start position)
- (int) End of the first block of strings (which seem to be the pose bindings ("keys"))
- (int) Start of the final 0xFF block which seems to be 4 bytes for each "key"

After the header at some point in the file (can't work out how you reliably find its position just yet, but it's before the first 0xFF block) there's the pose weighting data. The format of that is:

- (int) Key index (pose)
- (single) Value one
- (single) Value two

Seems to loop for a number of times giving values to each.

I'll keep looking into this.

**Comment by xPaw** [comment]
I suspect it hasn't really changed in years, so the code from 2007 engine leak could still apply:

https://github.com/VSES/SourceEngine2007/blob/master/src_main/utils/hlfaceposer/expclass.cpp#L196

**Comment by MattFiler** [comment]
Ah yeah, forgot about that - good shout. Will take a look.

**Comment by MattFiler** [comment]
Yep, still maps to the new source 2 files.

**Comment by muk-as** [comment]
VRF GUI can decompile vfe to txt
VRF Decompiler (with -d) return compiled vfe file
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/5202317/e10461de-5521-4a55-864b-70f9385a01ea)
