### ISSUE TITLE
Unhandled vcdlist_c in Dota 2

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveResourceFormat#160]
What is it?

**Comment by DatGuy1** [comment]
Compilation of .vcd files for a hero. .vcd make the hero avatars move when they speak and I think also include the subtitles

**Comment by KonqiTheKonqueror** [comment]
I made a guide on generating these files, perhaps it can be of use?: https://developer.valvesoftware.com/wiki/S2General/Importing_VCDs_to_Source_2
