### ISSUE TITLE
"Export As" all opened files

### ISSUE THREAD

**Issue by Ruuubickk** [ValveResourceFormat/ValveResourceFormat#174]
Currently in the GUI you have to manually select every single opened file and export as (in my case) png for vtex_c. Having the option to export all at once would be fantastic if possible.

**Comment by Ruuubickk** [comment]
Still hoping for this !

**Comment by xPaw** [comment]
You are more than welcome to contribute this feature yourself. No one is paid to work on this.

**Comment by kristiker** [comment]
Has been added in a previous release.

 ![Image](https://github.com/user-attachments/assets/7d022b31-0796-4677-9702-c28ce26908d6)
