### ISSUE TITLE
Lock folder tree from vpk in view for easier browsing & navigation

### ISSUE THREAD

**Issue by Wiethoofd** [ValveResourceFormat/ValveResourceFormat#179]
If you load a vpk and navigate the folder structure the right side of the window updates with what you click. When opening/viewing a file from the VPK it will be opened in a new tab, losing the original folder tree until you change or close the tab.

Keeping this navigation tree locked (or the option to do so) should make browsing, opening and viewing files a lot easier.

**Comment by xPaw** [comment]
Fixed by 404f7a79364e4919c6ac8fe905603a858524524f
