### ISSUE TITLE
Support export model with animation and wear item for model

### ISSUE THREAD

**Issue by phamtheson01** [ValveResourceFormat/ValveResourceFormat#251]
The export with animation is kinda like this:

![image](https://user-images.githubusercontent.com/45394243/83476710-9bec0f80-a4bb-11ea-92f2-00d284c02f0a.png)

and the second feature is kinda like this:

![image](https://user-images.githubusercontent.com/45394243/83477355-47499400-a4bd-11ea-866f-c662c55e16ce.png)

add the option to choose if someone wanna export LOD mesh or not

some bug I found:

Arc Warden missing body model
![image](https://user-images.githubusercontent.com/45394243/83477611-de165080-a4bd-11ea-87d5-908fc514c473.png)

![image](https://user-images.githubusercontent.com/45394243/83477637-ebcbd600-a4bd-11ea-9459-d76fd2c2b2ea.png)

Underlord body cant be exported

![image](https://user-images.githubusercontent.com/45394243/83477703-17e75700-a4be-11ea-9e02-f21e1e73207b.png)

**Comment by kristiker** [comment]
Exporting dota character with its wearables sounds too niche to be included by default in this project. Open separate issues for the other points (some issues already exist, so you can comment on them).
