### ISSUE TITLE
Register explorer file type associations

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveResourceFormat#49]
Like vmdl_c, vmesh_c, etc. We can use asset icons.

We can also register `vpk:` protocol to handle opening files directly inside of the vpk (vpk:path.vpk:file_inside.vmdl_c).

**Comment by SinZ163** [comment]
Don't explorer file type associations require some sort of installation to occur?

**Comment by Penguinwizzard** [comment]
You have to be able to change the user's registry settings, and preferably have your application somewhere reliably static.

**Comment by xPaw** [comment]
Gonna close this because we have vpk registering now, and registering individual files doesn't seem necessary because games always ship in vpks.
