### ISSUE TITLE
Certain models don't animate in GUI

### ISSUE THREAD

**Issue by moofMonkey** [ValveResourceFormat/ValveResourceFormat#494]
### Describe the bug

Exported glTF model animates correctly, however GUI doesn't seem to apply animations at all.
![idle](https://user-images.githubusercontent.com/11695747/209467370-658292e6-d5d2-4477-a95b-801eeca79025.png)
![idle](https://user-images.githubusercontent.com/11695747/209467416-f0314037-c586-45e2-94b8-34db63390103.png)
![cave_head_stone_fracture_new](https://user-images.githubusercontent.com/11695747/209467389-be83bc87-c184-4e0a-84fb-c2af90f61eed.png)
![cave_head_stone_fracture_new](https://user-images.githubusercontent.com/11695747/209467420-45b5066d-fdb0-4cb0-967d-9e4855cfe316.png)

### What Valve game does this happen in

Aperture Desk Job

### Reference file in a Source 2 game

Only one reference file so far, `models/cave_office/cave_head/cave_head_stone_fracture_new.vmdl`.

### Expected behavior

GUI should actually animate the model

### What version of VRF are you using? On what platform?

master, 6b14a61 so far

**Comment by kristiker** [comment]
The model VBIB lacks BLENDWEIGHTS, so it multiplies by zero in the vertex shader.

BLENDINDICES is RG1616_SINT, so is it two components or what?

https://github.com/ValveResourceFormat/ValveResourceFormat/blob/9ff82297fe2f5149aa08764d11455c539deac10b/GUI/Types/Renderer/Shaders/common/animation.glsl#L26-L33

**Comment by xPaw** [comment]
Extra models from #841

HL:A

models\ui\map_hologram_menu.vmdl_c

Desk Job

models/cave_office/cave_head/cave_head_stone_fracture_new.vmdl_c
models/toilet_intro/bullet_in_pipes.vmdl_c

**Comment by kristiker** [comment]
The commit above fixes the problem, but it needs to be implemented better.
![image](https://github.com/user-attachments/assets/f1441ddd-05b5-4560-92ba-f3f47515831f)
