### ISSUE TITLE
Ability to select extraction type for certain files when doing a folder extaction.

### ISSUE THREAD

**Issue by OykotGaming** [ValveResourceFormat/ValveResourceFormat#512]
### Is your feature request related to a problem? Please describe.

Whenever I extract an entire folder all Vmdl_C files are auto extracted to Gtilf. Or if I shift select extract it makes me select a extraction type for every single file separately.

### Describe the solution you'd like

Whenever I extract an entire folder all Vmdl_C files are auto extracted to Gtilf. I want the ability to be able to choose to auto decompile VMDL_C as VMDL. Or have the option when Shift selecting multiple file to Extract all selected files to a the option I choose instead of having to setup each extraction manually

**Comment by xPaw** [comment]
Try last unstable build.
