### ISSUE TITLE
Preview vsvg_c format files in VRF Tool

### ISSUE THREAD

**Issue by thouravi** [ValveResourceFormat/ValveResourceFormat#533]
### Is your feature request related to a problem? Please describe.

It would be awesome if we can preview these valve SVG files in the VRF tool itself, currently, it needs to be decompiled and saved in a directory to preview them. An option to preview these files in the tool will be awesome however not a priority at all.

### Describe the solution you'd like

Preview Valve SVG files in the tool itself without decompiling it.

### Describe alternatives you've considered

Current alternative is to decompile and save it on your system to preview it.

**Comment by xPaw** [comment]
While not impossible (there are libraries for it), SVG is very complicated and for the few files that exist as svg in Valve games, I don't think bringing in a big library to support is worth it. You can export them and view them in a browser.

**Comment by kristiker** [comment]
Facepunch is using [Svg.Skia](https://github.com/wieslawsoltes/Svg.Skia), seems to be lightweight: https://steamdb.info/patchnotes/11319824/
