### ISSUE TITLE
Incorrect export of bones for dynamic props on the map

### ISSUE THREAD

**Issue by vladhvorost** [ValveResourceFormat/ValveResourceFormat#543]
### Describe the bug

When exporting a map from a dota 2, random props do not have bones, but axis, in addition, many axis are not tied to the model, and these same axis 100% must be bones, since their names are called the names of the bones in the model, and there are animations
![axis_bones_export_problem](https://user-images.githubusercontent.com/114579552/232760826-88dbe7a1-d268-49d6-8f95-146a9ddb14c7.png)

### What game does this happen in

Dota 2

### Reference file in a Source 2 game

dota 2 beta\game\dota\maps\dota.vpk - dota\world.vwrld_c - Any maps Dota 2

### Expected behavior

To make models have bones, not axes

### What version of VRF are you using? On what platform?

0.3.2

**Comment by xPaw** [comment]
I'm gonna close this. Please test the latest version and provide more details if this issue still exists.
