### ISSUE TITLE
Dota 2 normal map export turn orange

### ISSUE THREAD

**Issue by Devostated** [ValveResourceFormat/ValveResourceFormat#591]
### Describe the bug

As I tried to export a Dota 2 character I got the different texture maps. The normal maps turned out completely orange, so I checked the reference material and it's textures. In the VRF view the normal map looked fine and I exported it without the model. The export was fine now.
Also tested decompiling and exporting the .vmat, which also lead into an orange normal map. I've noticed that the vmat export changed the name of my tested file from `windrunner_normal_psd_38977de9` to `windrunner_normal`. The linked vtex file is called `windrunner_normal_psd_38977de9.vtex`.

For reference here are the Windrunner face normal maps:
Exported together with the model:
![windrunner_normal_psd_38977de9](https://github.com/SteamDatabase/ValveResourceFormat/assets/30211694/cb3091d7-4714-4ea4-9b67-51e4e5685a2f)

Exported individually:
![windrunner_normal_psd_38977de9_Individual](https://github.com/SteamDatabase/ValveResourceFormat/assets/30211694/6620af97-1369-4d20-ab75-cbabd129e1b1)

### Relevant log output or exception with stacktrace

```shell
[13:27:10.132] Extracting windrunner.vmdl_c to "windrunner.gltf"
[13:27:10.592] Creating mesh: windrunner.vmdl_c.windranger_base
[13:27:10.600] Loading material: materials/models/heroes/windrunner/windrunner_base.vmat
[13:27:10.612] Waiting for materials to finish exporting...
[13:27:10.633] [1/1] Exporting texture: windrunner_color_psd_cb3528ab.vtex
[13:27:10.668] [2/2] Exporting texture: windrunner_normal_psd_38977de9.vtex
[13:27:10.716] [3/3] Exporting texture: windrunner_detailmask_tga_7d862a03_orm_4035109894.png
[13:27:10.718] Writing model to file 'windrunner.gltf'...
[13:27:12.041] Export completed in 00:00:01.9135412.
```

### What game does this happen in

Dota 2

### Reference file in a Source 2 game

models/heroes/windrunner/windrunner.vmdl_c

materials/models/heroes/windrunner/windrunner_base.vmat_c

materials/models/heroes/windrunner/windrunner_normal_psd_38977de9.vtex_c

### Expected behavior

It's expected to have a proper normal map when the normal map texture gets exported through material and model export. 

### What version of VRF are you using? On what platform?

v4.0.2078

**Comment by kristiker** [comment]
Must be bad instructions: remaping Alpha to Red thinking its DXTnm, but since alpha is 1.0 it results in orange color.

**Comment by Devostated** [comment]
I just noticed that this also happens with CS2
