### ISSUE TITLE
Failed to load document kv3 data: No valid format conversion from 'modeldoc32' to 'modeldoc29'

### ISSUE THREAD

**Issue by WujekFoliarz** [ValveResourceFormat/ValveResourceFormat#596]
### Describe the bug

When I try to decompile gman.vmdl_c in pak01_000.vpk to vmdl, it creates three files:

gman.vmdl (1kb in size, won't open)
gman_gman.dmx (7132kb in size, when exported to modeldoc only head and hands are present)
gman_gman_briefcase1.dmx (2541kb in size, model looks correct when exported to modeldoc)

When trying to open gman.vmdl in ModelDoc (S&Box) following error occurs:
`Failed to load document kv3 data: No valid format conversion from 'modeldoc32' to 'modeldoc29'`

### Relevant log output or exception with stacktrace

```shell
[13:40:31.401] Extracting gman.vmdl_c to "gman.vmdl"
[13:40:31.430] + gman.vmdl
[13:40:31.818] + gman_gman.dmx
[13:40:31.969] + gman_gman_briefcasel.dmx
[13:40:31.979] Export completed in 00:00:00.5761034.
```

### What game does this happen in

Half Life: Alyx

### Reference file in a Source 2 game

Half-Life Alyx/game/hlvr/pak01_dir.vpk/models/characters/gman/gman.vmdl_c

### Expected behavior

For the model to open correctly in ModelDoc

### What version of VRF are you using? On what platform?

v5.0.2126 Windows 11

**Comment by kristiker** [comment]
You can change the kv3 header in the vmdl file manually to the one that sbox accepts. At the moment we write CS2 version vmdl's but I guess we need to use something lower.

**Comment by WujekFoliarz** [comment]
is there a tutorial

**Comment by WujekFoliarz** [comment]
I opened the vmdl through cs2 and I still only get this, glTF export works fine though

![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/72314465/55b7b33c-c9aa-4689-a66a-82d4a63f3993)
