### ISSUE TITLE
Vertex Color support for exporting VWRLD_C

### ISSUE THREAD

**Issue by phoondos** [ValveResourceFormat/ValveResourceFormat#597]
### Is your feature request related to a problem? Please describe.

I'd like to port maps to blender as faithfully to the original as I can, which is not possible if vertex colors are not exported.

### Describe the solution you'd like

Vertex colors exported when exporting a vwrld as glb/gltf, so the displacement painting actually works in blender when combined with a proper material setup

### Describe alternatives you've considered

Painting it myself, but I'd have to crossreference the game/vrf preview

**Comment by pjoe** [comment]
I've seen that vert colors are exported, but somehow not correct:
![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/1846572/6fa4d4d8-cf46-4224-9ede-f605d70923dc)

Above is some tree branches from de_mirage where I hooked vert color directly into shaders base color.

Smells a bit like an offset or padding issue, or the order of the components (RGB) are just wrong

Changing the order becomes:
![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/1846572/f0a4aa76-595a-4f35-b265-8be97c7dfa60)

**Comment by kristiker** [comment]
@pjoe Generally vertex color in foliage is used for plant animation. Figure 16-2 https://developer.nvidia.com/gpugems/gpugems3/part-iii-rendering/chapter-16-vegetation-procedural-animation-and-shading-crysis

**Comment by pjoe** [comment]
@kristiker Thanks for info, just wondering if there is some way to detect this (and then ignore from the glTF export - add add custom property to indicate). Maybe some property on related entity or something. Will see if I can decompile map and open in hammer to check.

**Comment by kristiker** [comment]
@pjoe Might be possible to check the vertex buffer input signature (INSG block in the associated material). Actual vertex coloring is rarely used and I believe has the semantic name `VertexPaintTintColor`, while this special foliage one is `Color`.

As for the original issue @phoondos we have some commits in the dev branch that makes it so all attributes are exported.
<img src="https://cdn.discordapp.com/attachments/775429805469597768/1139465295052939264/image.png">

^ terrain blend is in _TEXCOORD_4, I hope blender can make use of that?

**Comment by phoondos** [comment]
it could probably make use of that, so long as it's an attribute I can probably use it in the material to blend the two corresponding materials, but i assume that source2 also uses height-based blending based on what ive seen from dust2 on cs2

**Comment by kristiker** [comment]
I don't see it. Does it need to be actual vertex color?
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/5145c78e-905d-485a-8023-294d908ea224)

**Comment by xPaw** [comment]
Can you please report the key error here: https://github.com/KhronosGroup/glTF-Blender-IO/issues

Preferably with a small repro file for them, https://sandbox.babylonjs.com/ should be able to load the file.

**Comment by pjoe** [comment]
Checking, latest version, if still having issues, I'll open separate issue

**Comment by pjoe** [comment]
Opened https://github.com/ValveResourceFormat/ValveResourceFormat/issues/624

**Comment by xPaw** [comment]
I'm gonna close this. With refactored attribute exporting and upcoming fix in blender, it should be possible to at least get the data in there.
