### ISSUE TITLE
Optional all lowercase for bone names on GLTF export

### ISSUE THREAD

**Issue by Devostated** [ValveResourceFormat/ValveResourceFormat#605]
### Is your feature request related to a problem? Please describe.

Some Dota2 heroes seem to have difference in lower and uppercase bone names between the base character model and their "wearables". I was facing the issue with alchemist and bristleback, which causes me many problems to automate the entire process of combining wearables with the basemodel and also having animations working in Blender.

### Describe the solution you'd like

A setting that allows you to enable bone name to all lowercase would help porting assets by a great amount. 

### Describe alternatives you've considered

For myself I just hardcoded `bone.Name.ToLower()` in the GLTF exporter, which worked perfectly fine.

**Comment by xPaw** [comment]
I'm gonna close this because we're keeping the original bone names.
