### ISSUE TITLE
Distorted meshes after decompiling .vmap_c file

### ISSUE THREAD

**Issue by xKrasheR** [ValveResourceFormat/ValveResourceFormat#618]
### Describe the bug

Some meshes appear distorted in Hammer editor upon opening the decompiled .vmap file.

Here are some noticable examples:

**Decompiled map** - de_overpass

- **node000_world_lr0_agg234_61_chainlink_fence_001.vmdl**
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/27704558/ad17bb33-1026-4d6d-899d-e044126f1af6)
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/27704558/12708a8e-deaa-42bf-86ba-a269b15e29c1)
- **node000_world_lr0_agg389_31_maple_tree_bark_1.vmdl**
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/27704558/39d5540d-c6cc-407d-a577-446925b3e082)
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/27704558/efd23b81-38f3-40ca-9ab5-4cf556b3e332)
- **node000_world_lr0_agg232_28_cypress_a.vmdl**
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/27704558/737924d6-d267-41e4-a728-d36dde91f84a)
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/27704558/79009988-087c-4083-a6c1-b02dd8505445)

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

**de_overpass.vmap_c** which is contained in **game\csgo\maps\de_overpass.vpk**

### Expected behavior

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/27704558/0e36dda8-ca54-4254-aede-29659ac72ba8)
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/27704558/331ffd12-0f9c-4ba6-9f0f-c2ed5ef1ea51)

### What version of VRF are you using? On what platform?

v5.0.2244, Windows 10 22H2 19045.3324

**Comment by xPaw** [comment]
This likely due to `ToDmxMesh` not using correct vertex/index buffers and not using the start offsets, while gltf exporting handles these.

**Comment by kristiker** [comment]
Has been fixed!

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/d30e9178-1d0b-4325-a9c9-c05a0c7a422b)
