### ISSUE TITLE
Some bones missing from gltf exported cs2 weapon model

### ISSUE THREAD

**Issue by mR1SY** [ValveResourceFormat/ValveResourceFormat#621]
### Describe the bug

**VMDL_C Import**
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/127650188/656042c4-e0b4-4730-8d5b-f68f095ffbf8)
**GLTF Import**
![2](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/127650188/825bff3a-63db-4d52-968c-aa0121b97b5f)

### Describe the bug

```shell
I extracted the "weapon_rif_ak47.vmdl_c" model, which I performed the "Decompile & Export" process using VRF, with the "GLTF" format. The model I created with GLTF format is missing some bones.
```

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

[VMDL_C.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/12561859/VMDL_C.zip)
[GLTF.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/12561869/GLTF.zip)

### Expected behavior

GLTF must have 42 bones

### What version of VRF are you using? On what platform?

5.0.2236 / Windows 10 Pro

**Comment by xPaw** [comment]
This happens because we filter out bones by `ModelSkeletonBoneFlags.BoneUsedByVertexLod0`, removing that exports them just fine.
