### ISSUE TITLE
File loader in addon contexts prioritizes game instead of addon

### ISSUE THREAD

**Issue by kristiker** [ValveResourceFormat/ValveResourceFormat#623]
### Describe the bug

This causes any potential overrided assets to be loaded differently from the game, when viewing maps.

### Relevant log output or exception with stacktrace

```shell
-
```

### What game does this happen in

Any with addon system

### Reference file in a Source 2 game

-

### Expected behavior

File loader grabs addon files first.

### What version of VRF are you using? On what platform?

5.0

**Comment by xPaw** [comment]
This works correctly when addon is packed in a vpk.

What happens here is that we check all of the vpks first, and then check on disk paths.

For addons that aren't packaged into a vpk, it should check on disk path of the addon first.

**Comment by kristiker** [comment]
Resolved by e1a63bf050deeca41538f96443fed29727f6399f
