### ISSUE TITLE
Filter files by VPK

### ISSUE THREAD

**Issue by szmarczak** [ValveResourceFormat/ValveResourceFormat#625]
### Is your feature request related to a problem? Please describe.

Opening a `pak01_000.vpk` actually opens `pak01_dir.vpk`, which probably is expected. However, it's not possible to know what files are exactly stored in `pak01_000.vpk` file.

### Describe the solution you'd like

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/36894700/83dac33b-a54a-44c4-af8d-6ff94c6b0a2f)

### Describe alternatives you've considered

none.

**Comment by xPaw** [comment]
Why? You can program this with the library yourself if thats something you really need. The 001.vpk itself does not contain any metadata.

**Comment by szmarczak** [comment]
Just experimentally modding, so no need to rebuild the VPKs, just a single one to patch. Feel free to close if you think this is not a desirable feature.

**Comment by xPaw** [comment]
I don't particularly think it's worth the effort. Modding the contents directly wont work because the metadata has checksum for the file, and valve's created archives have md5 hashes of all the data.

**Comment by szmarczak** [comment]
One use case would be e.g. finding flashbang definitions and patching the VPK e.g. just to see in practice mode how flashes would look if they were dark instead.

I see that it's not worth the effort. Indeed, it's completely doable with code. Thanks for consideration!

**Comment by xPaw** [comment]
I'm not sure CS will let you modify vpk willy nilly. The flashbang effect is probably not in the vpk anyway

**Comment by kristiker** [comment]
Use the addon system with your custom map to modify, override or add new files.
