### ISSUE TITLE
Vwrld model textures don't look right

### ISSUE THREAD

**Issue by dexelbro** [ValveResourceFormat/ValveResourceFormat#627]
### Describe the bug

After decompiling and exporting a CS2 map into gltf, when I import the model into blender the mesh looks fine but the texture colors are wrong.

### What game does this happen in

CS 2

### Reference file in a Source 2 game

All .vwrld map files

### Expected behavior

The textures of the map look the way they do in the game 

### What version of VRF are you using? On what platform?

5.0, Windows 10

**Comment by Lifeismana** [comment]
Did you try on latest unstable?
https://vrf.steamdb.info/

**Comment by dexelbro** [comment]
yes, same thing

**Comment by kristiker** [comment]
Don't expect glTF materials to support Source 2 terrain blend effects out of the box.

Previous discussion: #597

**Comment by xPaw** [comment]
Gonna close as duplicate of #639 as that has more info.
