### ISSUE TITLE
Incorrectly decompiled textures for materials with funny texture names

### ISSUE THREAD

**Issue by PiMoNFeeD** [ValveResourceFormat/ValveResourceFormat#630]
### Describe the bug

I've been decompiling FBI materials from CS2 and they were looking very odd, completely different to what their original compiled materials look, I looked at reconstructed vmat and realized that there's two vtex references that have `_normal` in their name, I don't know how decompiler assigns textures within a vmat, but the point is, in my example material, `g_tAnisoGloss` and `g_tNormal` are different textures but both have `_normal` in their file name for some reason, and because of that, two `TextureNormal` entries appear in vmat, and the decompiled normal map ends up being the incorrect one (the first one referenced, which is `g_tAnisoGloss` and not `g_tNormal`)
On top of that, it assigns a rougness texture that is never referenced in original compiled vmat either, which I guess can only assume that decompiler assigns textures to vmat solely based on file names, which is obviously not good

I don't know what `g_tAnisoGloss` is even meant to be, there is no texture entry that's called anything similar, there's a checkbox that's called `Anisotropic Gloss` for the given shader (csgo character) but it doesn't give any texture entries to put that `g_tAnisoGloss` texture into
if I compare original material to decompiled one with correct normal map assigned, it still looks slightly different and I can only assume its because of that `Anisotropic Gloss` texture entry that can't be assigned

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/36343425/c1cb91e7-d46d-4f0f-a0f2-36c3e8dd7756)

### What game does this happen in

CS2

### Reference file in a Source 2 game

characters/models/ctm_fbi/materials/ctm_fbi_v2_body_varianta.vmat_c
characters/models/ctm_fbi/materials/ctm_fbi_v2_body_variantd.vmat_c
characters/models/ctm_fbi/materials/ctm_fbi_v2_body_variantf.vmat_c
characters/models/ctm_fbi/materials/ctm_fbi_v2_body_variantg.vmat_c
characters/models/ctm_fbi/materials/ctm_fbi_v2_body_varianth.vmat_c

### Expected behavior

Decompiler not putting incorrect texture entries

### What version of VRF are you using? On what platform?

v5.0.2353+a8c749544d1de0f794a5d92c5cde593d5edb3526

**Comment by kristiker** [comment]
> I don't know what g_tAnisoGloss is even meant to be, there is no texture entry that's called anything similar, there's a checkbox that's called Anisotropic Gloss for the given shader (csgo character) but it doesn't give any texture entries to put that g_tAnisoGloss texture into

That is cool. It seems to be a compiler generated texture. Takes in roughness and normal to produce anisotropic roughness. Our decompiler is overriding the already-clean normal with whatever this texture contains. So we need to skip extracting normal from it.

**Comment by PiMoNFeeD** [comment]
> > I don't know what g_tAnisoGloss is even meant to be, there is no texture entry that's called anything similar, there's a checkbox that's called Anisotropic Gloss for the given shader (csgo character) but it doesn't give any texture entries to put that g_tAnisoGloss texture into
> 
> That is cool. It seems to be a compiler generated texture. Takes in roughness and normal to produce anisotropic roughness. Our decompiler is overriding the already-clean normal with whatever this texture contains. So we need to skip extracting normal from it.

Makes sense, but why does it assign a roughness texture if it's not referenced by the material (even in asset browser)? Can it be that it gets compiled out in favor of that anisotropic gloss thing?

**Comment by kristiker** [comment]
The original material has one TextureRoughness input. Whether is more like the one in g_tNormal.A, or the one in g_tAnisoGloss.RG, I don't really know.
