### ISSUE TITLE
Terrain_Blend exporting partaly broken

### ISSUE THREAD

**Issue by TheHeavynator** [ValveResourceFormat/ValveResourceFormat#639]
### Describe the bug

what appears to be happening is the gltf exporter is making incorect assumptions about vertex data for some meshes, specifically for world meshes, there ~~colors exported as just white (in some cases have weird splotches around edges)~~ and the Terrain_Blend has incorrect or missing colors. ~~ive noticed this tends to happen whith objects that have both _TEXCORD_4 and col since objects that only have col seem to be ok eg trees with displacement masks~~ howerver these displacement masks dont show in the viewer when in the VertexColor view.
~~also in some cases vertex color is simply missing for some exported meshes~~.

![1](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/147299655/8bfb564e-9ba7-4458-99ff-3929914fda46)
~~the car here is missing its vertex colors here and only has a Terrain_Blend also it can be seen that the enviroment VertexColor is wrong.~~ (not the case because its actuly object tint.)

![2](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/147299655/1e4a06b6-ba33-4da0-9054-600eff5a6064)
here is how it should look.

![3](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/147299655/438285c7-97c0-42d3-aab2-9d399d44c029)
here the exported terrain blend is being misinterpreted i would guess.

![4](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/147299655/9a57a6c4-db82-4156-abbc-2cf865428f04)
and this is how the terrain blend should look.

![5](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/147299655/6516f956-bff9-4cea-9393-b64bb9ded7b6)
and these vertex colors dont display in the viewer at all.

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

maps\cs_italy\world.vwrld_c

### Expected behavior

i would expect the ~~VertexColors~~/Terrain_Blend would match those present in the viewer since the data is read corectly but not exported corectly ~~exept in cases where the vertex colors are exported corectly but dont show in the viewer~~.

### What version of VRF are you using? On what platform?

5.0.2403 win10

**Comment by kristiker** [comment]
Btw VertexColor in the viewer mostly displays *object tint*. Tints are indeed not exported in glTF. Maybe it can be exported as a single-attribute vertex color stream.

**Comment by TheHeavynator** [comment]
Oh I see, that would be nice to have tint exported as its own thing. though this means the "VertexColor" render mode is incorect in what its actually displaying so it would probably be a good idea to add an aditonal render mode for object tint.

**Comment by TheHeavynator** [comment]
made some corrections to this post.

**Comment by TheHeavynator** [comment]
looking at the raw vertex data it turns out the exported terrain blend atribute duplicates the data across the green and blue channles with the blue data visible in the viewer actuly being in the alpha.

**Comment by kristiker** [comment]
The export is good. The viewer moved alpha to the blue channel for visualization, which caused the confusion.
