### ISSUE TITLE
Camera points down when touching viewport after loading a pre-configured camera position

### ISSUE THREAD

**Issue by Skelun** [ValveResourceFormat/ValveResourceFormat#641]
### Describe the bug

I've imported some camera positions (getpos) from CS2 into **settings.txt**. But when I load the position, it points down right after I hover the viewport.

I transformed this: `setpos -500.390747 -1735.968750 19.687836000000004;setang -9.899885 32.480961 0.000000`
into this:
```json
		"Camera 0"
		{
			"0"	"-500.39075"
			"1"	"-1735.9688"
			"2"	"19.687836"
			"3"	"-9.899885"
			"4"	"32.48096"
		}
```

Video showing it happening:
https://youtu.be/v7xgs_Q7BWA

My **settings.txt**:
[settings.txt](https://github.com/ValveResourceFormat/ValveResourceFormat/files/12851539/settings.txt)

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

G:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\maps\de_anubis.vpk

### Expected behavior

The camera should stay at the same position when manipulating the viewport.

### What version of VRF are you using? On what platform?

v5.0.2120 on Windows 11 Pro

**Comment by xPaw** [comment]
Modifying settings directly is not something we support, press setpos button in the GUI while that command is in your clipboard, that should work.
