### ISSUE TITLE
Animation and Armature export when exporting VMDL

### ISSUE THREAD

**Issue by Angel-foxxo** [ValveResourceFormat/ValveResourceFormat#650]
### Is your feature request related to a problem? Please describe.

Trying to export a viewmodel from CS2, in order to edit it and recompile it to use in an addon, the vmdl exporter does not export the armature or any animations, making it impossible to reconstruct the original viewmodel.

### Describe the solution you'd like

I would like for the vmdl exported to export all animations and the armature

**Comment by kristiker** [comment]
Animations are now exported though not linked to vmdl file. Armature implemented in #676. Closing in favor of #664 (tracks linking and other features such as AnimEvents)
