### ISSUE TITLE
cli exits after unpack 1 file

### ISSUE THREAD

**Issue by muk-as** [ValveResourceFormat/ValveResourceFormat#654]
### Describe the bug

affected only with this extensions: .evendef .txt .res .vtt .eventactions and mb more
on build 2360 and up - only 1 file unpacked - fail
on build 2359 and down - all files unpacked - ok
gui all builds - ok

P.S. with .vxml_c .vts_c - all working on all builds
P.S.S. without flag -d with all extensions on builds 2360+ exits after unpack 1 file

```
cd %~dp0
Decompiler.exe --version
Decompiler.exe -i "DOTA2_CLIENT\game\dota\pak01_dir.vpk" -d -e "res" -o "%~dp0\pak01_dir"
pause
```

### What game does this happen in

Dota 2

### Reference file in a Source 2 game

 .evendef .txt .res .vtt .eventactions and mb more

### Expected behavior

all files must be unpacked

### What version of VRF are you using? On what platform?

build 2359 and down | Win 10.0.19045

**Comment by xPaw** [comment]
The 2360 build commit in question: 30879cb1b068cf71b3a2813597493ae86c6be907

**Comment by muk-as** [comment]
fixed
