### ISSUE TITLE
Bug in decompiled Dota 2 maps

### ISSUE THREAD

**Issue by METABYTECODE** [ValveResourceFormat/ValveResourceFormat#660]
### Describe the bug

Decompiled maps look empty

### What game does this happen in

Dota 2

### Reference file in a Source 2 game

For example: If we decompile dota.vpk, we will get dota.map and the data folder. And if you run these files in hammer, it will crash

### Expected behavior

If you decompile the map and try to run it in hammer, then there is no land. And if next to .vmap will be a folder with the components of this card, then hammer will crash

### What version of VRF are you using? On what platform?

latest

**Comment by METABYTECODE** [comment]
> "latest" is not a version number.

6.0

**Comment by kristiker** [comment]
We have meshes that look like this:
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/f22727d0-ae4b-485e-adbf-0cb115d62f35)

As physics shape inputs they work fine, but adding them as RenderMeshFiles crashes resourcecompiler. This behavior started recently with one of the engine updates.

Adding a blank `normal$0` stream there fixes resourcecompiler.

**Comment by kristiker** [comment]
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/533ba655-58c2-4214-870c-cbf73fc3b87f)
