### ISSUE TITLE
Full Red Screen when viewing cs2 maps world_physics.vmdl_c

### ISSUE THREAD

**Issue by Aureo3** [ValveResourceFormat/ValveResourceFormat#661]
### Describe the bug

When Viewing recently updated official cs2 maps' world_physics.vmdl_c files, full screen turns red and fps tanks when default group is included. Returns to normal when unchecking default group, but then you can't see certain level geometry. 

Preview video: https://youtu.be/8CD4MY6pfkM

### What game does this happen in

counter-strike 2

### Reference file in a Source 2 game

C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\maps

maps/de_inferno/world_physics.vmdl_c

### Expected behavior

being able to see full level physics geometry

### What version of VRF are you using? On what platform?

6.0.2449 on windows. Also happens on 6.0 on windows.

**Comment by kristiker** [comment]
RnHull struct has changed. Here is new (left) and old (right):
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/8976286a-e647-41d9-9e28-82a8ec506a7c)
