### ISSUE TITLE
Sound preview by clicking on it

### ISSUE THREAD

**Issue by pixeljammed** [ValveResourceFormat/ValveResourceFormat#667]
### Is your feature request related to a problem? Please describe.

It's a lot of extra button presses and extra tabs opened just to preview a sound (.vsnd_c)

### Describe the solution you'd like

I would appreciate it if there was an option to immediately preview/play a sound simply by clicking or right clicking on it.

**Comment by xPaw** [comment]
Sort of duplicate of #179

**Comment by xPaw** [comment]
> please consider adding

Pull requests are always welcome.

**Comment by xPaw** [comment]
Fixed by 404f7a79364e4919c6ac8fe905603a858524524f
