### ISSUE TITLE
support *.herolist_c as decompileable

### ISSUE THREAD

**Issue by muk-as** [ValveResourceFormat/ValveResourceFormat#671]
### Is your feature request related to a problem? Please describe.

as example, in dota2 - pak01_dir.vpk/scripts/heroes.herolist_c
VRF can read this file, but can't decompile&export.
[ExportFile] Export for "heroes.herolist_c" has no suitable extension

P.S. also with *.dat files
as example, in dota2 - pak01_dir.vpk/resource/subtitles/subtitles_abaddon_english.dat
VRF can read this file, but when press decompile&export will get original file

**Comment by kristiker** [comment]
Viewer should offer resource data block export no matter what. In this case DATA is text, but the resource is not registered in vrf. Mildly related to #541

With .dat files, I don't know what is a good export type.

**Comment by muk-as** [comment]
Export .dat files as JSON?
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/5202317/80aa8b47-e18f-4d7e-a8bb-454c17673fa9)
```
[
   {
      "Hash":3952443579,
      "HashText":2929807745,
      "Blocknum":0,
      "Offset":0,
      "Length":8,
      "Text":"Map"
   },
   {
      "Hash":1591094946,
      "HashText":1063679044,
      "Blocknum":0,
      "Offset":8,
      "Length":18,
      "Text":"MOVEMENT"
   }
]
```
