### ISSUE TITLE
Refactor ideas

### ISSUE THREAD

**Issue by kristiker** [ValveResourceFormat/ValveResourceFormat#673]
* IKeyValueCollection ContainsKey(k) && GetProperty(k) -> GetValueOrDefault(k) like in ParticleDefinitionParser
* LoadFile(file+ "_c") -> LoadFileCompiled(file)

**Comment by xPaw** [comment]
Replace rawVertices float array and EnsureSpaceForVertices in particle renderer with ArrayPool.Shared.

**Comment by xPaw** [comment]
Refactor particles trails/sprites to have more in common, then merge the separate shaders into one spritecard shader.
