### ISSUE TITLE
Cursed compiling world physics from decompiled map

### ISSUE THREAD

**Issue by AHDR3** [ValveResourceFormat/ValveResourceFormat#674]
### Describe the bug

When I decompile map and then compile it using Hammer every model on a map does not have collision. I guess it is because `world_physics.vmdl_c` decompiling is cursed. I attach bellow 3 screenshots: the first one shows `world_physics.vmdl_c` from original map, the second one shows map that have been decompiled and then compiled, the third one shows Hammer map building settings. Log output is Hammer map building log. 

![image_2023-12-04_02-51-35](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/84991657/9b2cfec8-cc57-41e9-a924-2dca6933e780)

![image_2023-12-04_02-51-43](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/84991657/c1f12d89-be2e-4648-96c9-dc0a16f62007)

![image_2023-12-04_02-56-56](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/84991657/141e6744-a1fe-4399-8766-b72d90c3f76d)

### Relevant log output or exception with stacktrace

```shell
https://pastebin.pl/view/8697b654
```

### What game does this happen in

Counter Strike 2

### Reference file in a Source 2 game

Counter-Strike Global Offensive\game\csgo\maps\de_mirage.vpk\de_mirage\world_physics.vmdl_c

### Expected behavior

Compiled map with geometry.
![image_2023-12-04_02-51-35](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/84991657/e3e8994f-d697-4420-be3e-420cbedc9903)

### What version of VRF are you using? On what platform?

v7.0.2508, Windows

**Comment by kristiker** [comment]
Press Ctrl+Shift+T on Editable world physics that the map decompiles with.

**Comment by AHDR3** [comment]
Thanks, works not perfect, but it is good for my work

**Comment by kristiker** [comment]
If you want the actual original physics of the map (warning: will not be editable!), open physics.vmdl in ModelDoc and change rendermesh to physics mesh, removing the material remap table.

**Comment by RiotNOR** [comment]
> If you want the actual original physics of the map (warning: will not be editable!), open physics.vmdl in ModelDoc and change rendermesh to physics mesh, removing the material remap table.

Would you be able to more descriptively explain how this is done?

**Comment by RiotNOR** [comment]
> Sorry that was wrong advice. Export world_physics.vmdl from the map vpk and add it as a static prop at 0,0,0.

Thank you very much! I _just_ did that and that seemed to have worked. For anyone with the same issue, you can either export and import as said, or change the already loaded in physics reference to point to the new exported file by clicking on "Editable World Physics" in the outliner and change the model reference name (should just be to remove "_edit" from the filename assuming you exported with default name and same location)
