### ISSUE TITLE
Decompiled and exported physics/collision have incorrect Collision Property.

### ISSUE THREAD

**Issue by RiotNOR** [ValveResourceFormat/ValveResourceFormat#675]
### Describe the bug

Kind of a two-parter:

Firstly, if one wants to export one of Valve's own maps, you cannot just export the maps folder as the map won't load up after compiling in Hammer. You'll have to export multiple pieces one-by-one. The physics file is one of these (along with entities folder).

Upon loading up Mirage with the physics file corrected, there will be multiple collision boxes that will block everything due to their collision properties are all set to "Default" after export. If you try to smoke off CT from outside T ramp it will be blocked. 

Export "world_physics.vmdl_c" over S2V's exported world_physics_edit.vmdl, and then load it up in ModelDoc. Scroll to the bottom in the Source Outliner. Find "world_physics_phys1983.dmx". This is the offending mesh for my particular issue. If you set the Collision Property to "player_clip" (unknown if this is correct, but it works for now) and build the map you'll now be able to properly shoot and do line-ups.

Unless I am fixing this in the wrong way, I believe all meshes in the exported physics file to all just be set to "Default" collision property.

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

world_physics.vmdl

### Expected behavior

Proper Collision Properties on meshes.

### What version of VRF are you using? On what platform?

v7.0.2509

**Comment by kristiker** [comment]
This was fixed for maps a couple versions ago. We now split the physics, delete the parts that match the hammer mesh, and create suitable AUTOPHYS materials, so it gets the same physics properties as the original map.
