### ISSUE TITLE
Jittery animation data

### ISSUE THREAD

**Issue by krotter0** [ValveResourceFormat/ValveResourceFormat#681]
### Describe the bug

Animations in S2V have a slight jitter on some bones. They're read incorrectly, as the same jitter is also present in exported animations (so not just a visual issue).
The issue is present on a lot of animations, but it's not very obvious on most of them.

---

I've tested three different previous vrf versions and the issue is there, but it's slightly different in all of them, with the oldest looking the best (jitter in torso might just be masked by the entire body jittering up a bit, but the hand clips less at the end too).

v0.2.2.1057:

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/65136069/c6630b08-6d56-45b1-92e8-62dc120ad452

v0.3.2.1621:

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/65136069/5e142b60-2c6a-48f0-a475-1a147b3648d1

v6.0.2455:

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/65136069/b1daf884-6073-4e44-9fc6-ebb0c15ff6aa

### What game does this happen in

HLA and CS2, probably every other game too

### Reference file in a Source 2 game

CS2:
animset_uiplayer.vmdl_c
animation t_loadout_ump45_spray
(look at head)

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/65136069/5da5601a-cb08-43e0-8272-c0f2747270fa

HLA:
uncombined_vortiguant.vmdl_c
animation @vort_substation_2019_vort_pod_freed
(left is ModelDoc, right is S2V; look at upper torso, and right hand on the last few frames)

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/65136069/5e3c5467-2a4b-4c04-9ec9-75a64849bc82

Skeleton in S2V:

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/65136069/15232ff8-4be7-4ab5-ba6a-a2763a46fbda

### Expected behavior

Smooth animations

### What version of VRF are you using? On what platform?

7.0, Windows 10

**Comment by xPaw** [comment]
The likely culprit here is CCompressedDeltaVector3 decoder.
