### ISSUE TITLE
Tint Masks for some props are not exported correctly

### ISSUE THREAD

**Issue by adenexvfx** [ValveResourceFormat/ValveResourceFormat#685]
### Describe the bug

Tint mask textures for props exports as 1x1 px images. Tried to export with decompiler, same result. 

![img](https://i.imgur.com/jlYsmh9.png)

when I'm trying to open image with S2V it looks like this
![img](https://i.imgur.com/ryQnUrZ.png)

image must be 2048x2048 px, but exports as 1x1
![img](https://i.imgur.com/r8PKUKc.png)
![img](https://i.imgur.com/RquQO1n.png)

mask texture in cs2 sdk tools
![img](https://i.imgur.com/ayo1Kmm.png)

### Relevant log output or exception with stacktrace

```shell
[14:18:44.735] Extracting swat_van_generic_mask_tga_3dd12c1e.vtex_c to "swat_van_generic_mask_tga_3dd12c1e.png"
[14:18:44.835]   + swat_van_generic_mask_tga_3dd12c1e.png
[14:18:44.841] Export completed in 00:00:00.1100634.
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

`models/vehicles/swat_van/swat_van_generic_mask_tga_3dd12c1e.vtex_c`
`models/vehicles/trike/trike_body_clean_mask_tga_cbefbf68.vtex_c`
`models/vehicles/trike/trike_trailer_clean_mask_tga_6e0a8834.vtex_c`
`models/vehicles/vespa/vespa_1_mask_tga_cf531412.vtex_c`
`models/generic/terrace_set_01/terrace_tablecloth_01_tintmask_tga_984ff013.vtex_c`
`materials/models/props/de_dust/palace_pillars_vmat_g_ttintmask_2b2ebb3f.vtex_c`
etc.

### Expected behavior

expected the correct texture's resolution

### What version of VRF are you using? On what platform?

S2V v7.0.2479 (win)

**Comment by kristiker** [comment]
VRF assumes it is 1x1 as per these lines of code:
https://github.com/ValveResourceFormat/ValveResourceFormat/blob/7580dea284fad409fa62ee8f82766de5f2b4b39f/ValveResourceFormat/Resource/ResourceTypes/Texture.cs#L142-L143

Why are those values set to 1 here.
