### ISSUE TITLE
support subtitles *.dat as decompileable

### ISSUE THREAD

**Issue by muk-as** [ValveResourceFormat/ValveResourceFormat#686]
### Is your feature request related to a problem? Please describe.

as example, in dota2 - pak01_dir.vpk/resource/subtitles/subtitles_abaddon_english.dat
VRF can read this file, but when press decompile&export will get original file

### Describe the solution you'd like

Export subtitles *.dat files as JSON?
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/5202317/4ac31e15-bcc4-484a-94da-c353f31e0faa)
```
[
   {
      "Hash": 3952443579,
      "HashText": 2929807745,
      "Blocknum": 0,
      "Offset": 0,
      "Length": 8,
      "Text": "Map"
   },
   {
      "Hash": 1591094946,
      "HashText": 1063679044,
      "Blocknum": 0,
      "Offset": 8,
      "Length": 18,
      "Text": "MOVEMENT"
   }
]
```

**Comment by muk-as** [comment]
with Decompiler.exe
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/5202317/0516713b-0eeb-4d6e-85f8-67945c8f4512)

**Comment by xPaw** [comment]
We would dump it as keyvalues, not json.

But do you actually need the offsets or block nums for anything? I think the only relevant parts here is "hash -> text"

**Comment by muk-as** [comment]
"hash -> text" is ok!
P.S. Hash - it's hash from keys in *.vsndevts_c

**Comment by kristiker** [comment]
This can use the new `FileExtract.TryExtractNonResource`
