### ISSUE TITLE
SteamVR home pak02_dir.vpk not mounted

### ISSUE THREAD

**Issue by kristiker** [ValveResourceFormat/ValveResourceFormat#693]
Trying to open SteamVR Home map
`steamapps\common\SteamVR\tools\steamvr_environments\game\steamtours_addons\steamvr_home\pak01_dir.vpk`
->
`maps/steamvr_home.vpk`
->
`maps/steamvr_home.vmap_c`

Leads to missing skybox material `materials/skyboxes/sky_vesper_peak.vmat` which can be found on PAK_02 in base game
```
steamapps\common\SteamVR\tools\steamvr_environments\game\steamtours\pak02_dir.vpk
```

**Comment by xPaw** [comment]
It doesn't find base game at all because steamtours_addons has no gameinfo.gi to point to it.
