### ISSUE TITLE
Windows reports malicious content

### ISSUE THREAD

**Issue by e1m1j** [ValveResourceFormat/ValveResourceFormat#701]
### Describe the bug

When you run the .exe for Source2Viewer you get the following message:

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/86807353/32626959-c516-46e1-9078-2be5db4f0b04)

### What game does this happen in

Windows

### Reference file in a Source 2 game

N/A

### Expected behavior

Don't prompt

### What version of VRF are you using? On what platform?

Latest stable + unstable as of 17 Jan 2024

### Notes

While this is an understandable compromise for independent developers, I made an issue here in case anyone wonders why the software produces this message. The reason may be obvious to some but not all users.

Maybe we could get together and provide the team with enough donations to cover a Microsoft security certificate to stop this from flagging.

OR

Simply state that this is a common issue in the FAQ.

**Comment by xPaw** [comment]
This popup does not say it's malicious, it happens because the binary isn't signed.

**Comment by e1m1j** [comment]
> This popup does not say it's malicious, it happens because the binary isn't signed.

The insinuation is there, as Windows says there is a risk, and that's the only reason this was made as an issue in the first place. I know a few people who have tried using this software but have not made it past the unsigned warning. This issue is just letting people know that this is totally normal for unsigned software.
