### ISSUE TITLE
Bad render in some of the maps of hla

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#705]
### Describe the bug

Open a3_distillery.vpk (hla) and see how the render behaves 

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/51e63def-6f30-4736-ba69-4213bdab212e

### What game does this happen in

Half life alyx 

### Reference file in a Source 2 game

path: SteamLibrary\steamapps\common\Half-Life Alyx\game\hlvr\maps
map: a3_distillery.vpk

### Expected behavior

it should not happend

### What version of VRF are you using? On what platform?

7.0.2479 (Windows 10 pro)

**Comment by kristiker** [comment]
Issue was `models/props/xen/xen_villi_medium.vmdl` vertex buffer is missing vBLENDINDICES, despite there being more than one bone in the model.
