### ISSUE TITLE
Another hla bug render 

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#712]
### Describe the bug

Bad render in a3_distillery.vpk/a4_c17_zoo.vpk, the issue is the same as in #705

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/96f7ebe1-781d-4bb1-99a3-6a6d6f2ae323

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/33befaae-c2af-4079-8383-6c150938b5db)

### What game does this happen in

half life alyx

### Reference file in a Source 2 game

 a3_distillery.vpk
a4_c17_zoo.vpk

### Expected behavior

It shound not happend 

### What version of VRF are you using? On what platform?

v8.0.2968 (Windows 10 Pro)

**Comment by xPaw** [comment]
I can't repro this on either map.

**Comment by Unusuario2** [comment]
are you using the v8.0.2968 version? becouse happends in more maps (like in a4_c17_tanker_yard.vpk (hla))
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/6d710bfe-b909-4699-a8a0-6440a391d507)

**Comment by Unusuario2** [comment]
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/c76c0d39-7c0c-4e51-8e62-ae34aa1bd6c2)

**Comment by notfrying1pans** [comment]
Are you using amd?

**Comment by Unusuario2** [comment]
my hardware is amd ryzen 7 5800x and rtx 3060 ti

**Comment by kristiker** [comment]
Should be fixed in latest unstable release.
