### ISSUE TITLE
Complete frezze 

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#713]
### Describe the bug

1. Open a4_c17_tanker_yard.vpk
2. Open a4_c17_tanker_yard.vmap_c
3. See how the program complete frezze (S2V when frezees can not be closed of anything {see the video bellow}). 

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/e7a8d99d-bf7e-4402-bb6d-1d662fde1ce1

### What game does this happen in

Half life alyx

### Reference file in a Source 2 game

 a4_c17_tanker_yard.vpk

### Expected behavior

The program should not frezze

### What version of VRF are you using? On what platform?

v8.0.2968 (Windows 10 Pro)

**Comment by kristiker** [comment]
Loads although I got IndexOutOfRangeException window

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/cd92eb0a-6172-45a6-b87e-5e3d37634813)

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/1bec7c5a-7d6e-44f1-9f93-5c4bc19b9da0)

Value of that was -22, Lifetime 0, Age very big.

**Comment by xPaw** [comment]
I can't repro this (nor do I get any dialog like kristi). Try pressing ALT key, which should focus any existing dialog windows.

**Comment by Unusuario2** [comment]
yes, pressing ALT key does solve the issue.
