### ISSUE TITLE
Light Probes not working on AMD GPU

### ISSUE THREAD

**Issue by kristiker** [ValveResourceFormat/ValveResourceFormat#721]
### Reproduce steps for AMD devs
* AMD gpu
* Download https://valveresourceformat.github.io/
* Open texture file found here: [simple_3d_texture.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/14232526/simple_3d_texture.zip)
* Should have colors instead of black. Console should not have any [OpenGL] [High Api Error] messages.

### Describe the bug

Latest unstable build from https://valveresourceformat.github.io/

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/56fa3efc-fc21-4a06-9c21-f10044a19104)

After replacing DSA immutable texture storage calls with older API:
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/11a0987b-8f82-4c9c-a60a-82f2f305b57a)

Latest driver.

### Relevant log output or exception with stacktrace

```shell
[OpenGL] [High Api Error] glTextureStorage3D has generated an error (GL_INVALID_OPERATION)
[OpenGL] [High Api Error] glCompressedTextureSubImage3D has generated an error (GL_INVALID_OPERATION)
[OpenGL] [High Api Error] glTextureStorage3D has generated an error (GL_INVALID_OPERATION)
[OpenGL] [High Api Error] glCompressedTextureSubImage3D has generated an error (GL_INVALID_VALUE)
```

The patch to fix the issue looks like this:
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/f9f8b0c5-d276-4961-aeb1-3d60e088e761)

**Comment by Slaw6820** [comment]
It is fixed with future AMD driver (March or May).

**Comment by xPaw** [comment]
Do you have a link or something?

**Comment by Slaw6820** [comment]
https://community.amd.com/t5/newcomers-start-here/opengl-issue-with-texturestorage3d/m-p/670463/highlight/true#M2990

**Comment by SamboyCoding** [comment]
New AMD Software: Adrenalin Edition 24.6.1 is out today and this issue appears to be fixed in it.
