### ISSUE TITLE
Improve rendering of physics groups

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveResourceFormat#725]
At some point we changed rendering physics as triangles, so all the vertices need to be triangulated correctly, which is not the case for spheres.

Also, viewing physics outside of maps should draw over the model, because they currently clip into the model:
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/613331/7cd7eec7-dfc0-4a16-8a79-000048dce354)

Inspiration:
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/613331/40f2426b-77ed-4aa5-816f-59a163574129)

**Comment by kristiker** [comment]
Spheres and cylinders are now triangulated. And map physics now render with tooltextures. Should be good?
