### ISSUE TITLE
Issue with decompiling, prop_static are in 0,0,0

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#736]
### Describe the bug

When decompile vr_aperture_main.vpk all the static props are center of the map an not in their original coordinates

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/8756e6b1-ca65-400a-9dfb-3971094773c4

### What game does this happen in

Steamvrperformnacetest

### Reference file in a Source 2 game

vr_aperture_main.vpk

### Expected behavior

in hammer all the props should be at 0,0,0

### What version of VRF are you using? On what platform?

v8.1.0-unstable

**Comment by kristiker** [comment]
Need to use m_vTransform value from sceneObject here https://github.com/ValveResourceFormat/ValveResourceFormat/blob/36667375d95977993a312e35e9780ff8028b32f6/ValveResourceFormat/IO/MapExtract.cs#L453

**Comment by Unusuario2** [comment]
do you mean this?
void SceneObjectToStaticProp(KVObject  m_vTransform, int layerIndex, List<MapNode> layerNodes)
