### ISSUE TITLE
when decompiling an old map the dmx file is corrupted 

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#738]
### Describe the bug

When you decompile an old map from steamvrperformance beta the .dmx files are not exported well so it cant be compiled in to an vmdl 

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/c66db9ef-bc75-43cb-8e0c-c17cb2e784d6

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/3371abfd-8ab8-4239-8c6d-3f1f0d0de59f)

### What game does this happen in

steamvrperformancetest beta

### Reference file in a Source 2 game

vr_valve.vpk
[vr_valve.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/14390064/vr_valve.zip)
[worldnode000_mesh_nocollapse37.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/14390092/worldnode000_mesh_nocollapse37.zip)

### Expected behavior

it shouldnt decompile the .dmx correctly 

### What version of VRF are you using? On what platform?

v8.1.0-unstable

**Comment by kristiker** [comment]
Probably fixed. Check latest and report back please.

**Comment by Unusuario2** [comment]
The export is fixed.
