### ISSUE TITLE
Fix decompilation for old maps 

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#741]
### Is your feature request related to a problem? Please describe.

When you decompile and old map (Steamvrperformancebeta) the dmx files generated cannot be compiled in the model doc becouse the dmx file has a wrong string in  "mtlName"

wrong string: "mtlName" "element"

right string:    "mtlName" "string"

if your modify the file and remove the wrong string, the .dmx file can be compile and works fine 

example:
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/3ae528b6-fea5-4f2c-a53e-5f3459717ada)

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/4f0207d8-a118-4be3-bc8f-7d9479226e4c

in order to test this behavior go to  https://github.com/ValveResourceFormat/ValveResourceFormat/issues/738, donwload vr_valve.zip and decompile it

### Describe the solution you'd like

fix the  "mtlName" string

**Comment by kristiker** [comment]
666f4da3c5796519deb67f7adc99b2529a2b9cf9
