### ISSUE TITLE
9.0 triggers antivirus

### ISSUE THREAD

**Issue by notfrying1pans** [ValveResourceFormat/ValveResourceFormat#748]
### Describe the bug

When trying to open the stable release of 9.0 it triggered Windows Defender.
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/49667761/2f3989a3-de5a-4ae0-824b-7aee5d9f87b3)

### What game does this happen in

Irrelevant

### Reference file in a Source 2 game

Irrelevant

### Expected behavior

The program does not falsely trigger an antivirus

### What version of VRF are you using? On what platform?

9.0

**Comment by xPaw** [comment]
Wacatac is bullshit. https://github.com/dotnet/runtime/issues/33745
