### ISSUE TITLE
Material decompilation make a wrong .vmat 

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#768]
### Describe the bug

when you decompile a material it generates a .vmat with a wrong source file. For example:
If you decompile `backstage_grate_001a.vmat_c` the reconstructed .vmat will look like this 
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/d4578f76-4755-4685-b20a-b9468048b310)
but the decompile texure will be not `materials/metal/backstage_grate_001a_color.png` instead will be named `backstage_grate_001a_color_psd_e3ed4a9a.png` so when you load into hammer it does not compile automatically.
[wrong_vmat.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/14968792/wrong_vmat.zip)

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/ebad5cc5-20e1-41ff-9da8-7cb4c9819aec

So instead, the recontructed .vmat shoud have the name of the compiled texure. Another example:
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/85d30b1b-2702-4aa7-a3b1-b6cc0e31150f)
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/f0dd1fb2-c82d-4e31-a87c-f81e5152ace3)

### Relevant log output or exception with stacktrace

```shell
none.
```

### What game does this happen in

SteamVrbeta

### Reference file in a Source 2 game

backstage_grate_001a.vmat_c

### Expected behavior

it shound not compile automatically.

### What version of VRF are you using?

9.0.3293

**Comment by kristiker** [comment]
This is failing due to one of these conditions:

* Texture is not found due to it being on desktop.
* Compiled shader is not found, due to material being in desktop.

Please place the assets to a directory where they would be readable by the Source 2 engine itself.
