### ISSUE TITLE
Add support to export any model to .fbx

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#769]
### Is your feature request related to a problem? Please describe.

When i decompile a model and try to load the mesh into hammer or modeldoc the only format that the programs can load are  .dmx .fbx or .obj but VRF only supports .glTF and .glb in the decompilation so i have to import then into blender and save them into .fbx which is time consuming

### Describe the solution you'd like

Add support for .fbx extension in decompilation

### Describe alternatives you've considered

none.

**Comment by kristiker** [comment]
dmx is supported by selecting vmdl decompile

**Comment by Unusuario2** [comment]
where?
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/8038f8ea-ecc2-4172-960c-7856e8f9c2e6)
