### ISSUE TITLE
Update the VSNDEVTS writer

### ISSUE THREAD

**Issue by SinZ163** [ValveResourceFormat/ValveResourceFormat#77]
Currently we blindly write whatever we read, and add half decent KV1 wrappers around the data so it becomes a valid source file, though this instantly falls apart when the data was KV3 as we have kv1 structure just to have a kv3 header and kv3 data in the middle which is bad.

**Proposed solution:** On the first entry, check if it starts with `<` or not _(is it a KV3 header)_ and if it does, either parse the data as KV3 or store it for later and strip the kv3 header, and then reassemble all the entries back together again with one kv3 header, and having kv3 objects for each entry, with the key being the name of the entry.

If it didn't start with `<`, effectively run with what we are already doing.

**Comment by kristiker** [comment]
`NTRO` and `SoundEventScript` resource type has been deleted, so the data now prints 'as is' for all versions of sound event files.
