### ISSUE TITLE
Unable to decompile vtex_c files

### ISSUE THREAD

**Issue by BLACKGAMER1221** [ValveResourceFormat/ValveResourceFormat#798]
### Describe the bug

simply can't decompile vtex_c files 
![adfsadfasaf](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/76135089/e448665c-3be1-43bc-915b-42a70191453e)

version: 10.0.3595 b43f88ee14fdf0da91faf781f9bc171492bf15e2 on Microsoft Windows NT 10.0.19044.0

game: dota2

### Expected behavior

extract png/image files from vtex files 

### What game does this happen in

DOTA2

### Reference file in a Source 2 game

any dota2 vpk files with vtex_c files 

### What version of VRF are you using? Test latest dev build.

10.0.3595 b43f88ee14fdf0da91faf781f9bc171492bf15e2 on Microsoft Windows NT 10.0.19044.0

**Comment by xPaw** [comment]
Close this window and check the Console tab for any extra info. If nothing is there, check the windows event viewer.

**Comment by BLACKGAMER1221** [comment]
> Close this window and check the Console tab for any extra info. If nothing is there, check the windows event viewer.
> 
> This sounds like something is wrong with your OS though.

 console log: [21:26:53.818] [Console] Failed to load "surfaceproperties/surfaceproperties.vsurf_c"

**Comment by xPaw** [comment]
That's fine. Check event viewer. But this is the type of error that we can't really do anything to fix. You can try googling it, but there's also practically no useful info.

**Comment by BLACKGAMER1221** [comment]
> That's fine. Check event viewer. But this is the type of error that we can't really do anything to fix. You can try googling it, but there's also practically no useful info.

ok no problem, anyway thank you but here are the windows event log if can help,

Log Name:      Application
Source:        .NET Runtime
Date:          5/28/2024 9:33:14 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      *******************
Description:
Application: Source2Viewer.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at GUI.Types.Renderer.Framebuffer..ctor()
   at GUI.Types.Renderer.Framebuffer.Prepare(Int32, Int32, Int32, AttachmentFormat, DepthAttachmentFormat)
   at GUI.Types.Renderer.GLTextureDecoder.Initialize()
   at GUI.Types.Renderer.GLTextureDecoder.Initialize_NoExcept()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-05-28T18:03:14.5980898Z" />
    <EventRecordID>8192</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>**************</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Source2Viewer.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at GUI.Types.Renderer.Framebuffer..ctor()
   at GUI.Types.Renderer.Framebuffer.Prepare(Int32, Int32, Int32, AttachmentFormat, DepthAttachmentFormat)
   at GUI.Types.Renderer.GLTextureDecoder.Initialize()
   at GUI.Types.Renderer.GLTextureDecoder.Initialize_NoExcept()
</Data>
  </EventData>
</Event>

**Comment by xPaw** [comment]
What's your GPU and driver?

Are you able to open the texture or a map in app to view it?

**Comment by BLACKGAMER1221** [comment]
> What's your GPU and driver?
> 
> Are you able to open the texture or a map in app to view it?

i have really old GPU (GeForce 9500GT Driver 342.01)

about the textures or map  I didn't test it at this time (i am really new i don't know there is dota2 textures/ maps fles)

**Comment by xPaw** [comment]
Well you were trying to extract a texture, try to open it.

As for the driver, I don't think it even supports OpenGL 4.6 which we require, and I think that's why the texture decoder thread is failing. It should be falling back to software decode.

**Comment by BLACKGAMER1221** [comment]
> Well you were trying to extract a texture, try to open it.
> 
> As for the driver, I don't think it even supports OpenGL 4.6 which we require, and I think that's why the texture decoder thread is failing. It should be falling back to software decode.
> 
> Also, can you post full console log when the exception happens, was there `GL context failure` line?

yes i can't open it too
 and there is no other error

full log: 
- Welcome to Source 2 Viewer v10.0.3595+b43f88ee14fdf0da91faf781f9bc171492bf15e2
- If you are experiencing an issue, try using latest dev build from https://valveresourceformat.github.io/

[22:02:05.118] [MainForm] Opening C:\Users\asadaafd\Desktop\New folder (2)\mvp_default.vpk
[22:02:08.816] [Console] Failed to load "surfaceproperties/surfaceproperties.vsurf_c"

**Comment by xPaw** [comment]
Your GPU is unsupported.

**Comment by xPaw** [comment]
Can you try last dev build when it builds: https://github.com/ValveResourceFormat/ValveResourceFormat/actions/runs/9276264862

It should throw a message about unsupported opengl (and ideally allow you to decompile textures)
