### ISSUE TITLE
Colors are not displayed correctly on some models

### ISSUE THREAD

**Issue by SAH4RCOREJZ1337** [ValveResourceFormat/ValveResourceFormat#799]
### Describe the bug

Let's open the de_vertigo.vpk next de_vertigo.vmap_c and look at bombsite A. There should be red boxes there, but they are white. The color disappears in Source 2 Viewer 10.0. This happens not only with these boxes, but with some other objects too.
![2024-05-29 174948](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/57375481/f05c628d-8cb3-4ef6-b3b2-1396badb48d1)

### Expected behavior

In Source 2 Viewer 9.2 everything is fine, and the boxes are red. And all other objects have their own color as in the game.
![2024-05-29 174818](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/57375481/817a4ae8-1ca3-47a5-b79e-9ef830624081)

### What game does this happen in

CS2

### Reference file in a Source 2 game

C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\maps\de_vertigo.vpk

### What version of VRF are you using? Test latest dev build.

10.0

**Comment by kristiker** [comment]
Thanks. Has been fixed in dev build and on next version release.
