### ISSUE TITLE
Error about readonly_tools_asset_info.bin file

### ISSUE THREAD

**Issue by Bassquake** [ValveResourceFormat/ValveResourceFormat#825]
### Describe the bug

If I click on View Asset Info on any item in a vpk I get a popup:

![image](https://github.com/user-attachments/assets/ff089df8-a403-4da0-86f5-1e99503f9ef1)

I can't download the dev version to test with as Windows says the zip has a virus.

### Expected behavior

Show some info of selected item.

### What game does this happen in

Source 2 Viewer

### Reference file in a Source 2 game

Any file in Portal or Portal 2 (only games installed) vpk.

### What version of VRF are you using?

10.1.3729 6a8d02a98936c7c16ececfc0968b560c8efa4c01 on Microsoft Windows NT 10.0.19045.0 (GPU: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2, Driver: 4.6.0 NVIDIA 556.12)

**Comment by xPaw** [comment]
That's not a bug, asset info comes from that file, if it doesn't exist there's no info.  And Portal is not a S2 game so it won't have it.
