### ISSUE TITLE
Error when opening a model file

### ISSUE THREAD

**Issue by freddcurrys** [ValveResourceFormat/ValveResourceFormat#827]
### Describe the bug

When I want to open a weapon model, or map, instead of a showing of the model/map, I get a blackscreen instead in the viewport. As I get the blackscreen, in the console simultaneously comes this error loop: "[OpenGL] [High Api Error] GL_INVALID_OPERATION error generated. The SAMPLES values of the read and draw framebuffers should match.".
I already tried to install the latest version, deleting and reinstalling the software and I still have the same issues.
![Screenshot 2024-07-31 194828](https://github.com/user-attachments/assets/28cda9c8-eaaa-45e4-98aa-e2e638d4a36d)
![Screenshot 2024-07-31 194847](https://github.com/user-attachments/assets/901a4ab5-9eb7-4e93-b7c4-40434fe6e5ed)

### Expected behavior

Few months ago everything worked fine with no problems. But now, 31st July 2024, I got the issue as I wanted to check something of the models

### What game does this happen in

-

### Reference file in a Source 2 game

![Screenshot 2024-07-31 195322](https://github.com/user-attachments/assets/c2e5c319-5679-44d3-a547-fc87b4d612e6)

This also happens for other models and maps

### What version of VRF are you using?

10.1.3729 6a8d02a98936c7c16ececfc0968b560c8efa4c01

**Comment by xPaw** [comment]
Duplicate #723

**Comment by freddcurrys** [comment]
> Duplicate #723

Alright, thanks for the quick help!
