### ISSUE TITLE
Incorrect rendering of meshes with large amounts of joints

### ISSUE THREAD

**Issue by THG327** [ValveResourceFormat/ValveResourceFormat#841]
### Describe the bug

Models with a large joint count are not skinned correctly within the GUI. Exports are unaffected by this bug.

### Expected behavior

Models should be skinned as they appear in the export instead of being skinned to incorrect bones or to a single joint

### What game does this happen in

HLA / Dota 2 / Aperture Desk job

### Reference file in a Source 2 game

I have only tested the following but I assume this includes models in #265

HL:A

models\ui\map_hologram_menu.vmdl_c

Desk Job

models/cave_office/cave_head/cave_head_stone_fracture_new.vmdl_c
models/toilet_intro/bullet_in_pipes.vmdl_c

### What version of VRF are you using?

10.2.3850 4f2f81e04a752675cb4c31ee6572d4c53e0bb321 on Microsoft Windows NT 10.0.19045.0 (GPU: NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2, Driver: 4.6.0 NVIDIA 561.09)

**Comment by xPaw** [comment]
Is it related to #494?

**Comment by THG327** [comment]
yes. sorry for the duplicate issue

**Comment by THG327** [comment]
yes. sorry for the duplicate issue
