### ISSUE TITLE
Directional light problem

### ISSUE THREAD

**Issue by SAH4RCOREJZ1337** [ValveResourceFormat/ValveResourceFormat#842]
### Describe the bug

![Image](https://github.com/user-attachments/assets/74fdb148-243d-40ad-810f-09bfcc4db100)
After decompiling and building the map, the lighting in the game looks like this.
This happened after the recent update of cs2, maybe this is the problem, I don’t know.

### Expected behavior

It should look like this
![Image](https://github.com/user-attachments/assets/56934479-8bf4-48b0-afd6-25bbb085e30e)

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

de_mirage.vpk

### What version of VRF are you using?

10.2.3850 4f2f81e04a752675cb4c31ee6572d4c53e0bb321 on Microsoft Windows NT 10.0.22631.0 (GPU: NVIDIA GeForce RTX 4090/PCIe/SSE2, Driver: 4.6.0 NVIDIA 546.29)

**Comment by kristiker** [comment]
You need to set No Shadow on the model. The compiled map does not preserve this data, so we couldn't add it back.

**Comment by Angel-foxxo** [comment]
No this is not a decompiler bug at all, this is from back when valve broke light_rect, those artifacts were present after the armory update, they have since fixed it.

**Comment by kristiker** [comment]
Ah, ok, good.
