### ISSUE TITLE
Visualize navmesh in map viewer

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveResourceFormat#847]
### Is your feature request related to a problem? Please describe.

https://developer.valvesoftware.com/wiki/Nav_Mesh
https://developer.valvesoftware.com/wiki/Half-Life:_Alyx_Workshop_Tools/Level_Design/Navigation_Mesh

It should be the .nav file next to the vmap.

**Comment by eugen120320** [comment]
hello

**Comment by eugen120320** [comment]
hello

**Comment by Rhinovision** [comment]
hello
