### ISSUE TITLE
CS2 normal maps exports as black image.

### ISSUE THREAD

**Issue by cyberbemon** [ValveResourceFormat/ValveResourceFormat#852]
### Describe the bug

When exporting any CS2 normal map of a weapon skin via "Right click -> Decompile & Export" , the resulting image is just a black image. 

However, if I were to double click on the normal map and then use the "Save to disk" button from the preview window, the file is exported properly. It looks like the "decompile & export" via right click enables "YCoCG" conversion, because if I enable the "YCoCG" in the preview window, it results in the same black image, unchecking it resolves the issue.

### Expected behavior

Normal map file exported properly and not as a blank, black image. 

### What game does this happen in

Counter Strike 2

### Reference file in a Source 2 game

items/assets/paintkits/community/community_34/glock_chomper_normal_map_texture_tga_415a03f8.vtex_c

items/assets/paintkits/community/community_34/m249_hypnosis_normal_map_texture_tga_e35b8a7d.vtex_c

Any normal map textures under "items/assets/paintkits/" will work

### What version of VRF are you using?

10.2.3850 4f2f81e04a752675cb4c31ee6572d4c53e0bb321 on Microsoft Windows NT 10.0.22631.0 (GPU: NVIDIA GeForce RTX 4070 Laptop GPU/PCIe/SSE2, Driver: 4.6.0 NVIDIA 555.99)

**Comment by kristiker** [comment]
Its a problem with the image software. See #565

**Comment by cyberbemon** [comment]
> Its a problem with the image software. See [#565](https://github.com/ValveResourceFormat/ValveResourceFormat/issues/565)

The problem goes away when you use "Save to Disk" from the preview window though, I can open the image in affinity photo, photoshop etc without any issues.  If it was an issue with the image software, wouldn't it be present regardless of how its saved?

**Comment by kristiker** [comment]
Save To Disk is saving the image without transparency information since 'Opaque' channel mode is selected.

The texture in the game files contains an alpha channel with value 0.0, and the decompiled image is technically correct. Problem is image software ignores color information when alpha is 0.
