### ISSUE TITLE
Failed to decompile some vmat_c files

### ISSUE THREAD

**Issue by adenexvfx** [ValveResourceFormat/ValveResourceFormat#863]
### Describe the bug

some 'vmat_c' materials cannot be decompiled and exported via Source2Viewer or Decompiler.exe , the console throws an error and nothing else happens

### Expected behavior

Decompile material without errors

### Relevant log output or exception with stacktrace

```shell
[10:49:34.599] Extracting fabric_damaged.vmat_c to "fabric_damaged.vmat"
[10:49:34.601] Failed to extract 'fabric_damaged.vmat_c': Unexpected v64 value for variable 'AdditionalFiles': 3 (0x3)
[10:49:34.605] 1 files failed to extract, check console for more information.
[10:49:34.609] Export completed in 00:00:00.0074366.
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

from `...\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\pak01_dir.vpk
`
```
materials/de_overpass/nature/clay_ground_footprints_1.vmat_c
materials/de_train/hr_train_s2/plaster/hrts2_plaster_lath_01.vmat_c
materials/fabric/fabric_damaged.vmat_c
```

etc

### What version of VRF are you using?

10.2.3850 4f2f81e04a752675cb4c31ee6572d4c53e0bb321 on Microsoft Windows NT 10.0.22631.0 (GPU: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2, Driver: 4.6.0 NVIDIA 566.03)

**Comment by xPaw** [comment]
use dev build
