### ISSUE TITLE
Loading File Crashed

### ISSUE THREAD

**Issue by dragonlage** [ValveResourceFormat/ValveResourceFormat#868]
### Describe the bug

When I use it preview Hero's vmdl_c and other file. After Loading File stage it is crashed. 
I am using MacOS with Parallel's Desktop support. 
I can provide further information

### Expected behavior

I can use it preview file

### Relevant log output or exception with stacktrace

```shell

```

### What game does this happen in

source game

### Reference file in a Source 2 game

Any file from VPK

### Have you tried the latest dev build?

Yes

### What version of VRF are you using?

V10.2 and previously version

**Comment by xPaw** [comment]
There's no actionable information here.

**Comment by dragonlage** [comment]
![Image](https://github.com/user-attachments/assets/c6ce89ea-b439-4e1b-a750-1c25414dae03)

Double click vmdl_c it is crashed

**Comment by xPaw** [comment]
Gonna assume it's crashing because of opengl when running under parallels. Gonna close this because I can't think of much that we could do to fix this.

**Comment by dragonlage** [comment]
I have searched Parallel installed lower version of  OpenGL. Have to use VRF.exe older version preview contents.
