### ISSUE TITLE
Decompiling breaks trigger_push

### ISSUE THREAD

**Issue by SpsZaPIZZA** [ValveResourceFormat/ValveResourceFormat#869]
### Describe the bug

In the meaning of
 {
	pushdir = “ValveResourceFormat.Serialization.KeyValues.KVObject”
}
![Image](https://github.com/user-attachments/assets/07e46122-5ee6-4a33-bb5e-65facf21678d)

### Expected behavior

1

### Relevant log output or exception with stacktrace

```shell

```

### What game does this happen in

CS2

### Reference file in a Source 2 game

[Map Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=3142070597)

### Have you tried the latest dev build?

Yes

### What version of VRF are you using?

10.2.3959 71415825e2b95f2af0f55615b5f6da83f78ddef7 on Microsoft Windows NT 10.0.19045.0 (GPU: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2, Driver: 4.6.0 NVIDIA 566.14)

**Comment by xPaw** [comment]
> Reference file in a Source 2 game
Map Workshop

At least post the map.

**Comment by SpsZaPIZZA** [comment]
Added

**Comment by SpsZaPIZZA** [comment]
Sorry I was wrong , it happened when I dexopilized not on dev version, on dev build everything is fine
