### ISSUE TITLE
Crashes on launch after v11.0

### ISSUE THREAD

**Issue by PiMoNFeeD** [ValveResourceFormat/ValveResourceFormat#881]
### Describe the bug

All versions starting from v11.0 just don't work, they load for a second and then disappear from task manager. Every previous version works fine. After reading the changelog, I tried installing .NET 9 (Runtime and Desktop Runtime), it wasn't installed but installing it didn't help. I also tried downloading S2V to a different folder, starting as admin, nothing worked.

### Expected behavior

...

### Relevant log output or exception with stacktrace

No idea where to get the log file, or if it even exists outside of the program's console window

### What game does this happen in

...

### Reference file in a Source 2 game

...

### Have you tried the latest dev build?

Yes

### What version of VRF are you using?

v11.1

**Comment by xPaw** [comment]
What windows build? Look in event viewer for issues.

**Comment by PiMoNFeeD** [comment]
This is what I get from event viewer:
```
Version=1
EventType=APPCRASH
EventTime=133794323414859594
ReportType=2
Consent=1
UploadTime=133794323416975887
ReportStatus=268435456
ReportIdentifier=f2d559ae-653b-4a78-adf8-3c392386d6b3
IntegratorReportIdentifier=4ecade22-ea0d-42aa-8c39-5e89a8116a08
Wow64Host=34404
NsAppName=Source2Viewer.exe
OriginalFilename=Source2Viewer.dll
AppSessionGuid=00002d9c-0002-0319-aaba-886f3a55db01
TargetAppId=W:0000b9eabee6d3e2332cb589941d29124cc600000904!00002fb407c4ecc3d81a3577bb17168fe13c16c79cb4!Source2Viewer.exe
TargetAppVer=2024//10//29:02:40:27!af1f02d!Source2Viewer.exe
BootId=4294967295
TargetAsId=3559
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=1482cc09500c7629828b0ca11144ee8f
Response.BucketTable=4
Response.LegacyBucketId=1336175600364482191
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=Source2Viewer.exe
Sig[1].Name=Application Version
Sig[1].Value=11.1.4050.0
Sig[2].Name=Application Timestamp
Sig[2].Value=67204b1b
Sig[3].Name=Fault Module Name
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=10.0.19041.2913
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=a1c3e870
Sig[6].Name=Exception Code
Sig[6].Value=c0000602
Sig[7].Name=Exception Offset
Sig[7].Value=000000000012d862
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.19045.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1049
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=c9de
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=c9de323ee1574dea66483561d30d200d
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=0d6c
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=0d6c320702b364c55743b881f004ad99
UI[2]=E:\Downloads\Source2Viewer.exe
LoadedModule[0]=E:\Downloads\Source2Viewer.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[5]=C:\Windows\System32\msvcrt.dll
LoadedModule[6]=C:\Windows\System32\sechost.dll
LoadedModule[7]=C:\Windows\System32\RPCRT4.dll
LoadedModule[8]=C:\Windows\System32\ole32.dll
LoadedModule[9]=C:\Windows\System32\ucrtbase.dll
LoadedModule[10]=C:\Windows\System32\combase.dll
LoadedModule[11]=C:\Windows\System32\GDI32.dll
LoadedModule[12]=C:\Windows\System32\win32u.dll
LoadedModule[13]=C:\Windows\System32\gdi32full.dll
LoadedModule[14]=C:\Windows\System32\msvcp_win.dll
LoadedModule[15]=C:\Windows\System32\USER32.dll
LoadedModule[16]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[17]=C:\Windows\System32\SHELL32.dll
LoadedModule[18]=C:\Windows\System32\IMM32.DLL
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19045
OsInfo[3].Key=ubr
OsInfo[3].Value=2965
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1049
OsInfo[7].Key=geoid
OsInfo[7].Value=203
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222987730
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.789.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32677
OsInfo[19].Key=svolsz
OsInfo[19].Value=232
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.2965.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Source2Viewer
AppPath=E:\Downloads\Source2Viewer.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=BABCAB31EBF2A9FAED588770F6648AC8
MetadataHash=-1265492931
```

**Comment by xPaw** [comment]
Either your windows is somehow broken, or dotnet has a bug (but if it does I would expect more reports of this). Since the runtime is out of our control I don't know if we can do anything to solve this.

**Comment by PiMoNFeeD** [comment]
I ran v11.1 code in debugger and like usual with .NET, it also gave me a bunch of nothing:
```The program '[5076] Source2Viewer.exe' has exited with code 3221227010 (0xc0000602) 'The process aborted due to a fail fast exception.'.```
I was able to get it running by recompiling it for .NET 8.0 manually (and fixing like 3 errors total that were related to new threading syntax), which makes me question why did you even need to upgrade to 9.0 if there's basically zero difference, although I don't blame you for calling this crash a me issue; I'll keep investigating it for now, in case anyone else has it too, because I really don't like the idea of recompiling it from sources myself every time :)

**Comment by xPaw** [comment]
Are you crashing for an empty winforms project in net9? And it's crashing for a normal build, not just single file publish?

**Comment by PiMoNFeeD** [comment]
I am in fact crashing for an empty winforms project using .NET 9 but not .NET 8, and on both normal build and a single file publish, I also tried release and debug builds and uninstalling all the other .NET runtimes I had in my system (6.0 and 7.0), and I still crash

**Comment by xPaw** [comment]
Well if you can figure something out, make an issue in dotnet.

**Comment by PiMoNFeeD** [comment]
So I found out that running a console app gives me an extra error line:
```
CLR: Assert failure(PID 4452 [0x00001164], Thread: 20648 [0x50a8]): !AreShadowStacksEnabled() || UseSpecialUserModeApc()
    File: D:\a\_work\1\s\src\coreclr\vm\threads.cpp:7938
```
Googling that, it brought me to https://github.com/dotnet/runtime/issues/108589, which mentioned using `<CETCompat>false</CETCompat>` (https://learn.microsoft.com/en-us/dotnet/core/compatibility/interop/9.0/cet-support) and it did in fact fix my crash issue, I am now able to run .NET 9.0 apps. I am still gonna go ahead and create an issue on dotnet repo, but you might want to consider doing something similar to that parameter for S2V in the future

**Comment by xPaw** [comment]
Why is your Windows not updated anyway, if you updated to latest patch it probably would work.

**Comment by PiMoNFeeD** [comment]
> Why is your Windows not updated anyway, if you updated to latest patch it probably would work.

Because Windows updates are more likely to bring more bloat and/or break things than to fix something, this is in fact the only issue I've had so far that _might_ be related to an old Windows installation, though I am very sceptical about it because the guy from the aforementioned issue updated their year-old Windows build to another year-old Windows build that actually matches mine, and it worked for them, but me running the same build obviously doesn't

**Comment by fpsplay** [comment]
the same.i can't open v11 while v10 can open.
win10 22h2 19045.2728

**Comment by xPaw** [comment]
Well, same response to you as the last guy: update your Windows.

**Comment by xtance** [comment]
Hello, do you mean I should update to win11 or just latest 10? 

Can confirm the issue on LTSC 21H2

**Comment by PiMoNFeeD** [comment]
> Hello, do you mean I should update to win11 or just latest 10?
> 
> Can confirm the issue on LTSC 21H2

Doesn't matter, both work
